development:
  host: 0.0.0.0
  port: 9042
  keyspace: testcassandra

test:
  host: 0.0.0.0
  port: 9042
  keyspace: testcassandra

production:
  hosts:
    - 0.0.0.0
  port: 9042
  keyspace: testcassandra
